name: 'Terraform Apply'

on:
  push:
    branches: ["main",  "develop"]
  workflow_dispatch:

env:
  TF_LOG: INFO

jobs:
  azure_terraform:
    name: 'Azure - Terraform Appy'
    runs-on: ubuntu-latest

    env:
      TF_VAR_location: ${{ vars.AZURE_LOCATION }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set environment variable
      id: set-env
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          echo "TF_VAR_environment=production" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
          echo "TF_VAR_environment=staging" >> $GITHUB_ENV
        else
          echo "TF_VAR_environment=default" >> $GITHUB_ENV
        fi

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform init

      # On push to main, build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve