name: Terraform Apply All Repos
on:
    workflow_dispatch:

env:
    GITHUB_OWNER: ${{ github.repository_owner }}
    GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
        run:
          shell: bash

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Apply Observability
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository_owner }}/tech-challenge-fiap-database-terraform/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_TOKEN  }} \
          --data '{"event_type": "Terraform Apply", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'